import { ExternalLink as ExternalLinkIcon, SquarePen } from "lucide-react";
import {
  Button,
  cn,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@bookmemory/ui";
import { ExternalLink } from "@/components/ExternalLink";
import { MouseEventHandler, useEffect, useRef, useState } from "react";
import { useSummary } from "@/features/bookmarks/providers/summary";
import { Loader } from "@/components/Loader";
import { useBookmarks } from "@/features/bookmarks/providers/bookmark";
import { TagMode } from "@/features/bookmarks/providers/bookmark/BookmarksProvider";
import { TagModeSelect } from "@/components/TagModeSelect";
import { TagItems } from "@/components/TagItems";

interface ViewBookmarkModalProps {
  onClose: () => void;
  onEdit: () => void;
}

export function ViewBookmarkModal({ onClose, onEdit }: ViewBookmarkModalProps) {
  const [tagMode, setTagMode] = useState<TagMode>("ignore");
  const { bookmark, addRelatedBookmarks, relatedBookmarks, setBookmark, isLoading } =
    useBookmarks();
  const { setSummary, summary, startSummary, isLoading: isLoadingSummary } = useSummary();
  const tags = bookmark?.tags?.map((tag) => tag.name) || [];

  const contentRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    // update related bookmarks when the bookmark or tag mode changes
    const bookmarkId = bookmark?.id;
    if (bookmarkId) {
      void addRelatedBookmarks({ bookmarkId, tag_mode: tagMode });
    }
  }, [addRelatedBookmarks, bookmark, tagMode]);

  useEffect(() => {
    // update the summary when the bookmark changes
    if (bookmark?.summary) {
      setSummary(bookmark.summary);
    }

    // 👇 scroll to the top when the bookmark changes
    if (contentRef.current) {
      contentRef.current.scrollTo({
        top: 0,
        behavior: "smooth", // or "auto" if you prefer instant
      });
    }
  }, [setSummary, bookmark, contentRef]);

  const onGenerateSummary: MouseEventHandler = async (event) => {
    event.preventDefault();
    const bookmarkId = bookmark?.id;
    if (bookmarkId) {
      void startSummary(bookmarkId);
    }
  };

  const onTagModeChange = (value: string) => {
    const tagMode = value as TagMode;
    setTagMode(tagMode);
    const bookmarkId = bookmark?.id;
    if (bookmarkId) {
      void addRelatedBookmarks({ bookmarkId, tag_mode: tagMode });
    }
  };

  return (
    <Dialog
      open
      onOpenChange={(isOpening) => {
        if (!isOpening) {
          onClose();
        }
      }}
    >
      <DialogContent
        ref={contentRef}
        className="
           w-[95vw]
           max-w-[95vw] sm:max-w-4xl!
           max-h-[95dvh]
           flex flex-col
           overflow-hidden
           overscroll-contain
        "
      >
        <div className="flex-1 overflow-y-auto overscroll-contain">
          <DialogHeader>
            <DialogTitle className="flex items-center justify-center gap-4 text-muted-foreground">
              Bookmark
              <SquarePen className="w-4 h-4 cursor-pointer" onClick={onEdit} />
            </DialogTitle>

            {bookmark?.description && (
              <DialogDescription className="sr-only">{bookmark.description}</DialogDescription>
            )}
          </DialogHeader>
          {/* url section */}
          {bookmark?.url && (
            <div>
              <span className="text-muted-foreground">URL: </span>
              <ExternalLink
                href={bookmark.url}
                className="inline-flex items-center gap-1 break-word"
              >
                {bookmark.url} <ExternalLinkIcon className="w-4 h-4" />
              </ExternalLink>
            </div>
          )}

          {/* title section */}
          <h1>
            <span className="text-muted-foreground break-word">Title: </span>
            {bookmark?.title}
          </h1>

          {/* description section */}
          <div className="flex items-center justify-between text-muted-foreground">
            <h2>Description: </h2>
            <span className="hidden sm:inline!">Generated by AI from page content ✨</span>
          </div>
          <p>{bookmark?.description}</p>

          {/* summary section */}
          <div className="flex items-center justify-between text-muted-foreground">
            <span>Summary: </span>
            {isLoadingSummary ? (
              <span className="hidden sm:inline!">
                Generating summary with AI <span className="ml-1 animate-pulse">✨</span>
              </span>
            ) : (
              <span className="hidden sm:inline!">Generated by AI from web search ✨</span>
            )}
            <Button
              variant="ghost"
              className="bg-accent/50 border"
              onClick={onGenerateSummary}
              disabled={isLoadingSummary}
            >
              Regenerate
              <span className={cn("inline sm:hidden!", isLoadingSummary && "animate-pulse")}>
                ✨
              </span>
            </Button>
          </div>
          <p>{summary || (isLoadingSummary ? "Generating..." : "")}</p>

          {/* tags section */}
          {tags.length > 0 && (
            <TagItems label={<span className="text-muted-foreground">Tags:</span>} tags={tags} />
          )}

          {/* related bookmarks section */}
          <div className="flex items-center justify-between text-muted-foreground">
            <h2>Related Bookmarks: </h2>
            {tags.length > 0 ? (
              <>
                <TagModeSelect tagMode={tagMode} onChange={onTagModeChange} />
                <span className="hidden md:inline!">Powered by semantic search ⚡</span>
              </>
            ) : (
              <span className="hidden sm:inline!">Powered by semantic search ⚡</span>
            )}
          </div>
          {isLoading ? (
            <Loader className="w-10 h-10" />
          ) : relatedBookmarks.length === 0 ? (
            <p className="text-muted-foreground">No related bookmarks found.</p>
          ) : (
            <ul>
              {relatedBookmarks.map((relatedBookmark) => (
                <li
                  key={relatedBookmark.id}
                  className="underline cursor-pointer"
                  onClick={() => setBookmark(relatedBookmark)}
                >
                  {relatedBookmark.title}
                </li>
              ))}
            </ul>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
