import { ExternalLink as ExternalLinkIcon, SquarePen } from "lucide-react";
import {
  Badge,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@bookmemory/ui";
import { ExternalLink } from "@/components/ExternalLink";
import { useEffect, useRef } from "react";
import { useSummary } from "@/features/bookmarks/providers/summary";
import { Loader } from "@/components/Loader";
import { useBookmarks } from "@/features/bookmarks/providers/bookmark";

interface ViewBookmarkModalProps {
  onClose?: () => void;
  onEdit: () => void;
}

export function ViewBookmarkModal({ onClose, onEdit }: ViewBookmarkModalProps) {
  const { bookmark, addRelatedBookmarks, relatedBookmarks, setBookmark, isLoading } =
    useBookmarks();
  const { setSummary, summary, startSummary, isLoading: isLoadingSummary } = useSummary();
  const contentRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    // add related bookmarks
    const bookmarkId = bookmark?.id;
    if (bookmarkId) {
      void addRelatedBookmarks({ bookmarkId });
    }

    // set the bookmark summary or load it if it's empty
    if (bookmark?.summary) {
      setSummary(bookmark.summary);
    } else if (bookmarkId) {
      startSummary(bookmarkId);
    }

    // 👇 scroll to the top when the bookmark changes
    if (contentRef.current) {
      contentRef.current.scrollTo({
        top: 0,
        behavior: "smooth", // or "auto" if you prefer instant
      });
    }
  }, [bookmark, contentRef, setSummary, addRelatedBookmarks, startSummary]);

  return (
    <Dialog
      open
      onOpenChange={(isOpening) => {
        if (!isOpening) {
          onClose?.();
        }
      }}
    >
      <DialogContent
        ref={contentRef}
        className="
          w-[80vw] h-[80vh] max-w-4xl
          flex flex-col
          overflow-y-auto
        "
      >
        <DialogHeader>
          <DialogTitle className="flex items-center justify-center gap-1 text-muted-foreground">
            Bookmark
            <SquarePen className="w-4 h-4 cursor-pointer" onClick={onEdit} />
          </DialogTitle>

          {bookmark?.description && (
            <DialogDescription className="sr-only">{bookmark.description}</DialogDescription>
          )}
        </DialogHeader>
        {bookmark?.url && (
          <div>
            <span className="text-muted-foreground">URL: </span>
            <ExternalLink href={bookmark.url} className="inline-flex items-center gap-1">
              {bookmark.url} <ExternalLinkIcon className="w-4 h-4" />
            </ExternalLink>
          </div>
        )}
        <h1>
          <span className="text-muted-foreground">Title: </span>
          {bookmark?.title}
        </h1>
        <h2 className="flex justify-center text-muted-foreground">Description</h2>
        <p>{bookmark?.description}</p>
        {isLoadingSummary ? (
          <h2 className="flex justify-center text-muted-foreground">
            Generating summary with AI <span className="ml-1 animate-pulse">✨</span>
          </h2>
        ) : (
          <h2 className="flex justify-center text-muted-foreground">Summary generated by AI ✨</h2>
        )}
        <p>{summary}</p>
        <div className="flex flex-wrap gap-2">
          <span className="text-muted-foreground">Tags:</span>
          {bookmark?.tags?.map((tag) => (
            <Badge key={tag.id} variant="secondary">
              {tag.name}
            </Badge>
          ))}
        </div>
        <h2 className="flex justify-start text-muted-foreground">Related Bookmarks</h2>
        {isLoading ? (
          <Loader className="w-10 h-10" />
        ) : (
          <ul>
            {relatedBookmarks.map((relatedBookmark) => (
              <li
                key={relatedBookmark.bookmark.id}
                className="underline cursor-pointer"
                onClick={() => setBookmark(relatedBookmark.bookmark)}
              >
                {relatedBookmark.bookmark.title}
              </li>
            ))}
          </ul>
        )}
      </DialogContent>
    </Dialog>
  );
}
