import { ExternalLink as ExternalLinkIcon, SquarePen } from "lucide-react";
import {
  Badge,
  Button,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@bookmemory/ui";
import { ExternalLink } from "@/components/ExternalLink";
import { MouseEventHandler, useEffect, useRef, useState } from "react";
import { useSummary } from "@/features/bookmarks/providers/summary";
import { Loader } from "@/components/Loader";
import { useBookmarks } from "@/features/bookmarks/providers/bookmark";

interface ViewBookmarkModalProps {
  onClose: () => void;
  onEdit: () => void;
}

export function ViewBookmarkModal({ onClose, onEdit }: ViewBookmarkModalProps) {
  const [tagMode, setTagMode] = useState<"any" | "all" | "ignore">("ignore");
  const { bookmark, addRelatedBookmarks, relatedBookmarks, setBookmark, isLoading } =
    useBookmarks();
  const { setSummary, summary, startSummary, isLoading: isLoadingSummary } = useSummary();
  const tags = bookmark?.tags ?? [];

  const contentRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    // add related bookmarks
    const bookmarkId = bookmark?.id;
    if (bookmarkId) {
      void addRelatedBookmarks({ bookmarkId, tag_mode: tagMode });
    }

    // update the summary when the bookmark changes
    if (bookmark?.summary) {
      setSummary(bookmark.summary);
    }

    // 👇 scroll to the top when the bookmark changes
    if (contentRef.current) {
      contentRef.current.scrollTo({
        top: 0,
        behavior: "smooth", // or "auto" if you prefer instant
      });
    }
  }, [bookmark, contentRef, addRelatedBookmarks, setSummary]);

  const onGenerateSummary: MouseEventHandler = async (event) => {
    event.preventDefault();
    const bookmarkId = bookmark?.id;
    if (bookmarkId) {
      void startSummary(bookmarkId);
    }
  };

  const onTagModeChange = (value: string) => {
    setTagMode(value as "any" | "all" | "ignore");
    const bookmarkId = bookmark?.id;
    if (bookmarkId) {
      void addRelatedBookmarks({ bookmarkId, tag_mode: tagMode });
    }
  };

  return (
    <Dialog
      open
      onOpenChange={(isOpening) => {
        if (!isOpening) {
          onClose();
        }
      }}
    >
      <DialogContent
        ref={contentRef}
        className="
          w-[80vw] h-[80vh] max-w-4xl
          flex flex-col
          overflow-y-auto
        "
      >
        <DialogHeader>
          <DialogTitle className="flex items-center justify-center gap-4 text-muted-foreground">
            Bookmark
            <SquarePen className="w-4 h-4 cursor-pointer" onClick={onEdit} />
          </DialogTitle>

          {bookmark?.description && (
            <DialogDescription className="sr-only">{bookmark.description}</DialogDescription>
          )}
        </DialogHeader>
        {/* url section */}
        {bookmark?.url && (
          <div>
            <span className="text-muted-foreground">URL: </span>
            <ExternalLink href={bookmark.url} className="inline-flex items-center gap-1">
              {bookmark.url} <ExternalLinkIcon className="w-4 h-4" />
            </ExternalLink>
          </div>
        )}

        {/* title section */}
        <h1>
          <span className="text-muted-foreground">Title: </span>
          {bookmark?.title}
        </h1>

        {/* description section */}
        <div className="flex items-center justify-between text-muted-foreground">
          <h2>Description: </h2>
          <span>Generated by AI from page content ✨</span>
        </div>
        <p>{bookmark?.description}</p>

        {/* summary section */}
        <div className="flex items-center justify-between text-muted-foreground">
          <span>Summary: </span>
          {isLoadingSummary ? (
            <span>
              Generating with AI <span className="ml-1 animate-pulse">✨</span>
            </span>
          ) : (
            <>Generated by AI from web search ✨</>
          )}
          <Button
            variant="ghost"
            className="bg-accent/50 border"
            onClick={onGenerateSummary}
            disabled={isLoadingSummary}
          >
            Regenerate
          </Button>
        </div>
        <p>{summary || (isLoadingSummary ? "Generating..." : "")}</p>

        {/* tags section */}
        <div className="flex flex-wrap gap-2">
          <span className="text-muted-foreground">Tags:</span>
          {tags.map((tag) => (
            <Badge key={tag.id} variant="secondary">
              {tag.name}
            </Badge>
          ))}
        </div>

        {/* related bookmarks section */}
        <div className="flex items-center justify-between text-muted-foreground">
          <h2>Related Bookmarks: </h2>
          <span className="inline sm:hidden">Powered by semantic search ⚡</span>
          {tags.length > 0 && (
            <div className="flex items-center gap-2">
              Match tags:
              <Select value={tagMode} onValueChange={onTagModeChange}>
                <SelectTrigger className="w-fit cursor-pointer">
                  <SelectValue placeholder="Match tags" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem className="cursor-pointer" value="any">
                    Any
                  </SelectItem>
                  <SelectItem className="cursor-not-allowed" value="all">
                    All
                  </SelectItem>
                  <SelectItem className="cursor-not-allowed" value="ignore">
                    None
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>
          )}
        </div>
        {isLoading ? (
          <Loader className="w-10 h-10" />
        ) : relatedBookmarks.length === 0 ? (
          <p className="text-muted-foreground">No related bookmarks found.</p>
        ) : (
          <ul>
            {relatedBookmarks.map((relatedBookmark) => (
              <li
                key={relatedBookmark.id}
                className="underline cursor-pointer"
                onClick={() => setBookmark(relatedBookmark)}
              >
                {relatedBookmark.title}
              </li>
            ))}
          </ul>
        )}
      </DialogContent>
    </Dialog>
  );
}
