// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BookmarkCreateRequest
 */
export type BookmarkCreateRequest = {
    /**
     * Type
     *
     * bookmark type: link | note | file
     */
    type?: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * BookmarkPreviewRequest
 */
export type BookmarkPreviewRequest = {
    /**
     * Type
     */
    type?: string;
    /**
     * Url
     */
    url: string;
};

/**
 * BookmarkPreviewResponse
 */
export type BookmarkPreviewResponse = {
    /**
     * Type
     */
    type: string;
    /**
     * Url
     */
    url: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Load Method
     */
    load_method?: string | null;
    /**
     * Preview Method
     */
    preview_method?: string | null;
    /**
     * Content Preview
     */
    content_preview?: string | null;
};

/**
 * BookmarkResponse
 */
export type BookmarkResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Type
     */
    type: string;
    /**
     * Url
     */
    url: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Load Method
     */
    load_method: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Tags
     */
    tags: Array<TagResponse>;
};

/**
 * BookmarkSearchRequest
 */
export type BookmarkSearchRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Tag Mode
     */
    tag_mode?: 'any' | 'all' | 'ignore';
};

/**
 * BookmarkSearchResponse
 */
export type BookmarkSearchResponse = {
    bookmark: BookmarkResponse;
    /**
     * Snippet
     */
    snippet: string;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Chunk Id
     */
    chunk_id?: string | null;
};

/**
 * CurrentUser
 */
export type CurrentUser = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Picture Url
     */
    picture_url?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LimitOffsetPage[BookmarkResponse]
 */
export type LimitOffsetPageBookmarkResponse = {
    /**
     * Items
     */
    items: Array<BookmarkResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * TagCountResponse
 */
export type TagCountResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Count
     */
    count: number;
};

/**
 * TagResponse
 */
export type TagResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthApiV1HealthGetResponses = {
    /**
     * Response Health Api V1 Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthApiV1HealthGetResponse = HealthApiV1HealthGetResponses[keyof HealthApiV1HealthGetResponses];

export type VersionApiV1VersionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/version';
};

export type VersionApiV1VersionGetResponses = {
    /**
     * Response Version Api V1 Version Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type VersionApiV1VersionGetResponse = VersionApiV1VersionGetResponses[keyof VersionApiV1VersionGetResponses];

export type DbPingApiV1DbPingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/db/ping';
};

export type DbPingApiV1DbPingGetResponses = {
    /**
     * Response Db Ping Api V1 Db Ping Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DbPingApiV1DbPingGetResponse = DbPingApiV1DbPingGetResponses[keyof DbPingApiV1DbPingGetResponses];

export type GoogleStartApiV1AuthGoogleStartGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/google/start';
};

export type GoogleStartApiV1AuthGoogleStartGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GoogleCallbackApiV1AuthGoogleCallbackGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/google/callback';
};

export type GoogleCallbackApiV1AuthGoogleCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAuthenticatedUserApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetAuthenticatedUserApiV1UsersMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAuthenticatedUserApiV1UsersMeGetError = GetAuthenticatedUserApiV1UsersMeGetErrors[keyof GetAuthenticatedUserApiV1UsersMeGetErrors];

export type GetAuthenticatedUserApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: CurrentUser;
};

export type GetAuthenticatedUserApiV1UsersMeGetResponse = GetAuthenticatedUserApiV1UsersMeGetResponses[keyof GetAuthenticatedUserApiV1UsersMeGetResponses];

export type PreviewBookmarkApiV1BookmarksPreviewPostData = {
    body: BookmarkPreviewRequest;
    path?: never;
    query?: never;
    url: '/api/v1/bookmarks/preview';
};

export type PreviewBookmarkApiV1BookmarksPreviewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewBookmarkApiV1BookmarksPreviewPostError = PreviewBookmarkApiV1BookmarksPreviewPostErrors[keyof PreviewBookmarkApiV1BookmarksPreviewPostErrors];

export type PreviewBookmarkApiV1BookmarksPreviewPostResponses = {
    /**
     * Successful Response
     */
    200: BookmarkPreviewResponse;
};

export type PreviewBookmarkApiV1BookmarksPreviewPostResponse = PreviewBookmarkApiV1BookmarksPreviewPostResponses[keyof PreviewBookmarkApiV1BookmarksPreviewPostResponses];

export type GetBookmarksApiV1BookmarksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Query
         */
        query?: string | null;
        /**
         * Tag
         */
        tag?: Array<string>;
        /**
         * Tag Mode
         */
        tag_mode?: 'any' | 'all' | 'ignore';
        /**
         * Sort
         */
        sort?: 'alphabetical' | 'recent';
        /**
         * Limit
         *
         * Page size limit
         */
        limit?: number;
        /**
         * Offset
         *
         * Page offset
         */
        offset?: number;
    };
    url: '/api/v1/bookmarks/';
};

export type GetBookmarksApiV1BookmarksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBookmarksApiV1BookmarksGetError = GetBookmarksApiV1BookmarksGetErrors[keyof GetBookmarksApiV1BookmarksGetErrors];

export type GetBookmarksApiV1BookmarksGetResponses = {
    /**
     * Successful Response
     */
    200: LimitOffsetPageBookmarkResponse;
};

export type GetBookmarksApiV1BookmarksGetResponse = GetBookmarksApiV1BookmarksGetResponses[keyof GetBookmarksApiV1BookmarksGetResponses];

export type CreateBookmarkApiV1BookmarksPostData = {
    body: BookmarkCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/bookmarks/';
};

export type CreateBookmarkApiV1BookmarksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBookmarkApiV1BookmarksPostError = CreateBookmarkApiV1BookmarksPostErrors[keyof CreateBookmarkApiV1BookmarksPostErrors];

export type CreateBookmarkApiV1BookmarksPostResponses = {
    /**
     * Successful Response
     */
    200: BookmarkResponse;
};

export type CreateBookmarkApiV1BookmarksPostResponse = CreateBookmarkApiV1BookmarksPostResponses[keyof CreateBookmarkApiV1BookmarksPostResponses];

export type GetBookmarkApiV1BookmarksBookmarkIdGetData = {
    body?: never;
    path: {
        /**
         * Bookmark Id
         */
        bookmark_id: string;
    };
    query?: never;
    url: '/api/v1/bookmarks/{bookmark_id}';
};

export type GetBookmarkApiV1BookmarksBookmarkIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBookmarkApiV1BookmarksBookmarkIdGetError = GetBookmarkApiV1BookmarksBookmarkIdGetErrors[keyof GetBookmarkApiV1BookmarksBookmarkIdGetErrors];

export type GetBookmarkApiV1BookmarksBookmarkIdGetResponses = {
    /**
     * Successful Response
     */
    200: BookmarkResponse;
};

export type GetBookmarkApiV1BookmarksBookmarkIdGetResponse = GetBookmarkApiV1BookmarksBookmarkIdGetResponses[keyof GetBookmarkApiV1BookmarksBookmarkIdGetResponses];

export type LoadBookmarkApiV1BookmarksBookmarkIdLoadPostData = {
    body?: never;
    path: {
        /**
         * Bookmark Id
         */
        bookmark_id: string;
    };
    query?: never;
    url: '/api/v1/bookmarks/{bookmark_id}/load';
};

export type LoadBookmarkApiV1BookmarksBookmarkIdLoadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoadBookmarkApiV1BookmarksBookmarkIdLoadPostError = LoadBookmarkApiV1BookmarksBookmarkIdLoadPostErrors[keyof LoadBookmarkApiV1BookmarksBookmarkIdLoadPostErrors];

export type LoadBookmarkApiV1BookmarksBookmarkIdLoadPostResponses = {
    /**
     * Successful Response
     */
    200: BookmarkResponse;
};

export type LoadBookmarkApiV1BookmarksBookmarkIdLoadPostResponse = LoadBookmarkApiV1BookmarksBookmarkIdLoadPostResponses[keyof LoadBookmarkApiV1BookmarksBookmarkIdLoadPostResponses];

export type GetRelatedBookmarksApiV1BookmarksBookmarkIdRelatedGetData = {
    body?: never;
    path: {
        /**
         * Bookmark Id
         */
        bookmark_id: string;
    };
    query?: {
        /**
         * Tag Mode
         */
        tag_mode?: 'any' | 'all' | 'ignore';
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/bookmarks/{bookmark_id}/related';
};

export type GetRelatedBookmarksApiV1BookmarksBookmarkIdRelatedGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRelatedBookmarksApiV1BookmarksBookmarkIdRelatedGetError = GetRelatedBookmarksApiV1BookmarksBookmarkIdRelatedGetErrors[keyof GetRelatedBookmarksApiV1BookmarksBookmarkIdRelatedGetErrors];

export type GetRelatedBookmarksApiV1BookmarksBookmarkIdRelatedGetResponses = {
    /**
     * Response Get Related Bookmarks Api V1 Bookmarks  Bookmark Id  Related Get
     *
     * Successful Response
     */
    200: Array<BookmarkSearchResponse>;
};

export type GetRelatedBookmarksApiV1BookmarksBookmarkIdRelatedGetResponse = GetRelatedBookmarksApiV1BookmarksBookmarkIdRelatedGetResponses[keyof GetRelatedBookmarksApiV1BookmarksBookmarkIdRelatedGetResponses];

export type SearchBookmarksApiV1BookmarksSearchPostData = {
    body: BookmarkSearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/bookmarks/search';
};

export type SearchBookmarksApiV1BookmarksSearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchBookmarksApiV1BookmarksSearchPostError = SearchBookmarksApiV1BookmarksSearchPostErrors[keyof SearchBookmarksApiV1BookmarksSearchPostErrors];

export type SearchBookmarksApiV1BookmarksSearchPostResponses = {
    /**
     * Response Search Bookmarks Api V1 Bookmarks Search Post
     *
     * Successful Response
     */
    200: Array<BookmarkSearchResponse>;
};

export type SearchBookmarksApiV1BookmarksSearchPostResponse = SearchBookmarksApiV1BookmarksSearchPostResponses[keyof SearchBookmarksApiV1BookmarksSearchPostResponses];

export type StreamBookmarkSummaryApiV1BookmarksBookmarkIdSummaryPostData = {
    body?: never;
    path: {
        /**
         * Bookmark Id
         */
        bookmark_id: string;
    };
    query?: never;
    url: '/api/v1/bookmarks/{bookmark_id}/summary';
};

export type StreamBookmarkSummaryApiV1BookmarksBookmarkIdSummaryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamBookmarkSummaryApiV1BookmarksBookmarkIdSummaryPostError = StreamBookmarkSummaryApiV1BookmarksBookmarkIdSummaryPostErrors[keyof StreamBookmarkSummaryApiV1BookmarksBookmarkIdSummaryPostErrors];

export type StreamBookmarkSummaryApiV1BookmarksBookmarkIdSummaryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTagsApiV1TagsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tags';
};

export type GetTagsApiV1TagsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTagsApiV1TagsGetError = GetTagsApiV1TagsGetErrors[keyof GetTagsApiV1TagsGetErrors];

export type GetTagsApiV1TagsGetResponses = {
    /**
     * Response Get Tags Api V1 Tags Get
     *
     * Successful Response
     */
    200: Array<TagCountResponse>;
};

export type GetTagsApiV1TagsGetResponse = GetTagsApiV1TagsGetResponses[keyof GetTagsApiV1TagsGetResponses];
