"""users oauth identity and sessions

Revision ID: e9885d3454c4
Revises: 67c92d1920eb
Create Date: 2026-02-03 15:46:52.757741

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e9885d3454c4"
down_revision: Union[str, None] = "67c92d1920eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Needed for gen_random_uuid() default (safe if already installed).
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.create_table(
        "sessions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)

    op.add_column(
        "users", sa.Column("auth_provider", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "users", sa.Column("auth_subject", sa.String(length=255), nullable=False)
    )
    op.add_column("users", sa.Column("email", sa.String(length=320), nullable=False))
    op.add_column("users", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("picture_url", sa.String(length=2048), nullable=True)
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        "uq_users_auth_provider_subject",
        "users",
        ["auth_provider", "auth_subject"],
    )

    # Ensure users.created_at has a DB-side default.
    # Alembic doesn't retroactively apply SQLAlchemy model defaults unless the migration does it.
    op.execute("UPDATE users SET created_at = now() WHERE created_at IS NULL")
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=None,
        existing_nullable=False,
    )

    op.drop_constraint("uq_users_auth_provider_subject", "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "picture_url")
    op.drop_column("users", "name")
    op.drop_column("users", "email")
    op.drop_column("users", "auth_subject")
    op.drop_column("users", "auth_provider")

    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")

    # ### end Alembic commands ###
